cmake_minimum_required(VERSION 3.0...3.10)

if(NOT DEFINED ZX_COMPILER_FAMILY)
    set(ZX_COMPILER_FAMILY "clang")
endif()
if(NOT DEFINED ZX_C_COMPILER)
    set(ZX_C_COMPILER "clang")           # clang | gcc
endif()
if(NOT DEFINED ZX_CXX_COMPILER)
    set(ZX_CXX_COMPILER "clang++")       # clang | gcc
endif()
if(NOT DEFINED ZX_COMPILER_VERSION)
    set(ZX_COMPILER_VERSION "")          # e.g. "17" -> clang-17 / clang++-17
endif()
if(NOT DEFINED ZX_COMPILER_PREFIX)
    set(ZX_COMPILER_PREFIX "")           # cross-compiler prefix for gcc builds
endif()
if(NOT DEFINED ZX_OPT_LEVEL)
    set(ZX_OPT_LEVEL "2")                # 0,1,2,3,s,z
endif()
if(NOT DEFINED ZX_DSYM_LEVEL)
    set(ZX_DSYM_LEVEL "0")               # 0,1,2,3
endif()
if(NOT DEFINED ZX_MARCH_MODE)
    set(ZX_MARCH_MODE "z13")             # z13, z14, z15, z16 ...
endif()
if(NOT DEFINED ZX_DASD_SERIAL)
    set(ZX_DASD_SERIAL "001842095440")
endif()
if(NOT DEFINED ZX_BUILD_DIR)
    set(ZX_BUILD_DIR "build")
endif()
if(NOT DEFINED ZX_TOOLCHAIN_FILE)
    set(ZX_TOOLCHAIN_FILE "${ZX_BUILD_DIR}/toolchain.generated.cmake")
endif()
if(NOT DEFINED ZX_CONFIG_FILE)
    set(ZX_CONFIG_FILE "${ZX_BUILD_DIR}/config.generated.cmake")
endif()
if(NOT DEFINED ZX_NOCHECK)
    set(ZX_NOCHECK OFF)
endif()

set(_zx_valid_compilers clang gcc unknown)
set(_zx_valid_opt 0 1 2 3 s z)
set(_zx_valid_dsym 0 1 2 3)

set(_dash_dash_idx -1)
math(EXPR _loop_max "${CMAKE_ARGC} - 1")

foreach(i RANGE 0 ${_loop_max})
    if(CMAKE_ARGV${i} STREQUAL "--")
        set(_dash_dash_idx ${i})
        break()
    endif()
endforeach()

math(EXPR _command_start_idx "${_dash_dash_idx} + 1")
set(_zx_command "${CMAKE_ARGV${_command_start_idx}}")

if(_zx_command STREQUAL "" OR _zx_command STREQUAL "help" OR _zx_command STREQUAL "cmake") # index 0 is cmake itself
    message([[
ZXFoundation configuration helper tool. Copyright (C) 2026 assembler-0. Licensed under the Apache License, Version 2.0.

Usage:
    cmake [-D<OPTION>=<VALUE> ...] -P configure.cmake -- [<COMMAND> ...]

Options:
    ZX_COMPILER_FAMILY (*) [clang]   | gcc | unknown             (default: clang)
    ZX_C_COMPILER      (*) [clang]   | gcc | unknown             (default: clang)
    ZX_CXX_COMPILER    (*) [clang++] | g++ | unknown             (default: clang++)
    ZX_COMPILER_VERSION    version suffix, e.g. 17               (default: "")
    ZX_COMPILER_PREFIX     cross prefix (for gcc)                (default: "")
    ZX_OPT_LEVEL             0     1   [2]   3  s  z             (default: 2)
    ZX_DSYM_LEVEL           [0]    1    2    3                   (default: 0)
    ZX_MARCH_MODE          [z13]  z14  z15  z16 ...              (default: z13)
    ZX_DASD_SERIAL         12-digit DASD serial                  (default: 001842095440)
    ZX_BUILD_DIR           output directory                      (default: build)
    ZX_TOOLCHAIN_FILE      path for the generated toolchain file (default: $ZX_BUILD_DIR/toolchain.generated.cmake)
    ZX_CONFIG_FILE         path for the generated config file    (default: $ZX_BUILD_DIR/config.generated.cmake)
    ZX_NOCHECK             no check for standard safeguards      (default: ON)

Command:
    [help]             (X) shows this help                       (default)
    configure          (X) configures the project
    build              (X) configures and build the project
    genconfig          (X) generates configuration files

Notes:
    (*): Required option
    (X): Choose one of the options

Examples:
  cmake -P configure.cmake -- help
  cmake -P -DZX_C_OMPILER=clang -DZX_CXX_COMPILER=clang++ configure.cmake -- build
]])
    return()
endif()

if (NOT ZX_NOCHECK)
    list(FIND _zx_valid_compilers "${ZX_COMPILER_FAMILY}" _zx_idx)
    if(_zx_idx EQUAL -1)
        message(FATAL_ERROR "ZX_COMPILER_FAMILY must be one of: ${_zx_valid_compilers} (got '${ZX_COMPILER_FAMILY}')")
    endif()
    
    list(FIND _zx_valid_opt "${ZX_OPT_LEVEL}" _zx_idx)
    if(_zx_idx EQUAL -1)
        message(FATAL_ERROR "ZX_OPT_LEVEL must be one of: ${_zx_valid_opt} (got '${ZX_OPT_LEVEL}')")
    endif()
    
    list(FIND _zx_valid_dsym "${ZX_DSYM_LEVEL}" _zx_idx)
    if(_zx_idx EQUAL -1)
        message(FATAL_ERROR "ZX_DSYM_LEVEL must be one of: ${_zx_valid_dsym} (got '${ZX_DSYM_LEVEL}')")
    endif()
    
    if(NOT ZX_DASD_SERIAL MATCHES "^[0-9]+$")
        message(FATAL_ERROR "ZX_DASD_SERIAL must be numeric (got '${ZX_DASD_SERIAL}')")
    endif()
endif()

if (_zx_command STREQUAL "configure" OR _zx_command STREQUAL "build" OR _zx_command STREQUAL "genconfig")
    set(_tc "# Autogenerated by configure.cmake -- do not edit by hand\n")
    string(APPEND _tc "# ZXFoundation ${ZX_C_COMPILER}/${ZX_CXX_COMPILER} toolchain for s390x\n\n")
    string(APPEND _tc "set(CMAKE_SYSTEM_NAME Generic)\n")
    string(APPEND _tc "set(CMAKE_SYSTEM_PROCESSOR s390x)\n")

    if(ZX_COMPILER_VERSION STREQUAL "" AND ZX_COMPILER_VERSION STREQUAL "")
        set(_zx_cc "${ZX_C_COMPILER}")
        set(_zx_cxx "${ZX_CXX_COMPILER}")
    elseif(NOT ZX_COMPILER_VERSION STREQUAL "" AND ZX_COMPILER_PREFIX STREQUAL "")
        set(_zx_cc "${ZX_C_COMPILER}-${ZX_COMPILER_VERSION}")
        set(_zx_cxx "${ZX_CXX_COMPILER}-${ZX_COMPILER_VERSION}")
    elseif(ZX_COMPILER_VERSION STREQUAL "" AND NOT ZX_COMPILER_PREFIX STREQUAL "")
        set(_zx_cc "${ZX_COMPILER_PREFIX}-${ZX_C_COMPILER}")
        set(_zx_cxx "${ZX_COMPILER_PREFIX}-${ZX_CXX_COMPILER}")
    else()
        set(_zx_cc "${ZX_COMPILER_PREFIX}-${ZX_C_COMPILER}-${ZX_COMPILER_VERSION}")
        set(_zx_cxx "${ZX_COMPILER_PREFIX}-${ZX_CXX_COMPILER}-${ZX_COMPILER_VERSION}")
    endif()
    string(APPEND _tc "set(CMAKE_C_COMPILER ${_zx_cc})\n")
    string(APPEND _tc "set(CMAKE_CXX_COMPILER ${_zx_cxx})\n")
    string(APPEND _tc "set(CMAKE_ASM_COMPILER ${_zx_cc})\n\n")
    if(ZX_COMPILER_FAMILY STREQUAL "clang")
        string(APPEND _tc "set(CMAKE_LINKER ld.lld)\n")
        string(APPEND _tc "set(CMAKE_AR llvm-ar)\n")
        string(APPEND _tc "set(CMAKE_RANLIB llvm-ranlib)\n")
        string(APPEND _tc "set(CMAKE_OBJCOPY llvm-objcopy)\n")
        string(APPEND _tc "set(CMAKE_OBJDUMP llvm-objdump)\n")
        string(APPEND _tc "set(ZX_NM llvm-nm)\n")
        string(APPEND _tc "set(ZX_CXXFILT llvm-cxxfilt)\n")
        string(APPEND _tc "set(ZX_HOST_CC clang)\n\n")
        string(APPEND _tc "set(COMPILER_ID \"clang\")\n")
    else() # gcc and unknown
        if (NOT ZX_COMPILER_PREFIX STREQUAL "")
            string(APPEND _tc "set(CMAKE_LINKER ${ZX_COMPILER_PREFIX}-ld)\n")
            string(APPEND _tc "set(CMAKE_AR ${ZX_COMPILER_PREFIX}-ar)\n")
            string(APPEND _tc "set(CMAKE_RANLIB ${ZX_COMPILER_PREFIX}-ranlib)\n")
            string(APPEND _tc "set(CMAKE_OBJCOPY ${ZX_COMPILER_PREFIX}-objcopy)\n")
            string(APPEND _tc "set(CMAKE_OBJDUMP ${ZX_COMPILER_PREFIX}-objdump)\n")
            string(APPEND _tc "set(ZX_NM ${ZX_COMPILER_PREFIX}-nm)\n")
            string(APPEND _tc "set(ZX_CXXFILT ${ZX_COMPILER_PREFIX}-c++filt)\n")
            string(APPEND _tc "set(ZX_HOST_CC ${ZX_C_COMPILER})\n\n")
            string(APPEND _tc "set(COMPILER_ID \"${ZX_COMPILER_FAMILY}\")\n")
        else()
            string(APPEND _tc "set(CMAKE_LINKER ld)\n")
            string(APPEND _tc "set(CMAKE_AR ar)\n")
            string(APPEND _tc "set(CMAKE_RANLIB ranlib)\n")
            string(APPEND _tc "set(CMAKE_OBJCOPY objcopy)\n")
            string(APPEND _tc "set(CMAKE_OBJDUMP objdump)\n")
            string(APPEND _tc "set(ZX_NM nm)\n")
            string(APPEND _tc "set(ZX_CXXFILT c++filt)\n")
            string(APPEND _tc "set(ZX_HOST_CC ${ZX_C_COMPILER})\n\n")
            string(APPEND _tc "set(COMPILER_ID \"${ZX_COMPILER_FAMILY}\")\n")
        endif()
    endif()

    set(_cfg "# Autogenerated by configure.cmake -- do not edit by hand\n")
    string(APPEND _cfg "# Standard configuration\n\n")
    string(APPEND _cfg "set(OPT_LEVEL \"${ZX_OPT_LEVEL}\" CACHE STRING \"Optimization level (0, 1, 2, 3, s, z)\")\n")
    string(APPEND _cfg "set(DSYM_LEVEL \"${ZX_DSYM_LEVEL}\" CACHE STRING \"Debug symbol level (0, 1, 2, 3)\")\n")
    string(APPEND _cfg "set(MARCH_MODE \"${ZX_MARCH_MODE}\" CACHE STRING \"Architecture mode, for -march and -mtune\")\n")
    string(APPEND _cfg "set(DASD_SERIAL \"${ZX_DASD_SERIAL}\" CACHE STRING \"Dasd serial\")\n")

    get_filename_component(_zx_tc_dir "${ZX_TOOLCHAIN_FILE}" DIRECTORY)
    get_filename_component(_zx_cfg_dir "${ZX_CONFIG_FILE}" DIRECTORY)
    if(_zx_tc_dir)
        file(MAKE_DIRECTORY "${_zx_tc_dir}")
    endif()
    if(_zx_cfg_dir)
        file(MAKE_DIRECTORY "${_zx_cfg_dir}")
    endif()

    file(WRITE "${ZX_TOOLCHAIN_FILE}" "${_tc}")
    file(WRITE "${ZX_CONFIG_FILE}" "${_cfg}")
endif()

if (_zx_command STREQUAL "configure" OR _zx_command STREQUAL "build")
    execute_process(
        COMMAND ${CMAKE_COMMAND} -B ${ZX_BUILD_DIR} -DZX_TOOLCHAIN_FILE=${ZX_TOOLCHAIN_FILE} -DZX_CONFIG_FILE=${ZX_CONFIG_FILE} -GNinja
        RESULT_VARIABLE _zx_configure_result
    )
endif()

message(" ZXFoundation configure.cmake configuration overview:")
message("  Command         : ${_zx_command}")
message("  Compiler family : ${ZX_COMPILER_FAMILY} (${_zx_cc}/${_zx_cxx})")
message("  Optimization    : ${ZX_OPT_LEVEL}")
message("  Debug symbols   : ${ZX_DSYM_LEVEL}")
message("  Architecture    : ${ZX_MARCH_MODE}")
message("  DASD serial     : ${ZX_DASD_SERIAL}")
message("  Generated       : ${ZX_TOOLCHAIN_FILE}")
message("                    ${ZX_CONFIG_FILE}")
if (_zx_command STREQUAL "genconfig")
    message("Next steps:")
    message("  ${CMAKE_COMMAND} -B ${ZX_BUILD_DIR} -DZX_TOOLCHAIN_FILE=${ZX_TOOLCHAIN_FILE} -DZX_CONFIG_FILE=${ZX_CONFIG_FILE} -GNinja")
    message("  ${CMAKE_COMMAND} --build ${ZX_BUILD_DIR}")
elseif (_zx_command STREQUAL "configure")
    if (NOT _zx_configure_result EQUAL 0)
        message(WARNING "configure may have failed. please recheck your configuration.")
        message("configure.cmake: nothing to do. exiting")
        return()
    else ()
        message("Next steps:")
        message("  ${CMAKE_COMMAND} --build ${ZX_BUILD_DIR}")
    endif()
elseif (_zx_command STREQUAL "build")
    if (NOT _zx_configure_result EQUAL 0)
        message(WARNING "configure may have failed. please recheck your configuration.")
        message("configure.cmake: nothing to do. exiting")
        return()
    elseif (NOT _zx_build_result EQUAL 0)
        message(WARNING "build may have failed. please recheck your configuration.")
        return()
    endif()
endif()
message("configure.cmake: nothing to do. exiting")

