# ZXFoundation template toolchain file
message(FATAL_ERROR "zxfoundation::build: THIS IS A TEMPLATE TOOLCHAIN, DO NOT USE. PLEASE REMOVE THIS NOTE IF YOU ARE PLANNING TO USE THIS.") ## REMOVE after you have made your own toolchain
set(CMAKE_SYSTEM_NAME Generic)
set(CMAKE_SYSTEM_PROCESSOR s390x)

set(CMAKE_C_COMPILER <YOUR_C_COMPILER_HERE>)
set(CMAKE_CXX_COMPILER <YOUR_C++_COMPILER_HERE>)
set(CMAKE_ASM_COMPILER <YOUR_C/ASM_COMPILER_HERE>)

set(CMAKE_C_LINK_EXECUTABLE "<CMAKE_LINKER> <LINK_FLAGS> <OBJECTS> -o <TARGET> <LINK_LIBRARIES>")
set(CMAKE_LINKER <YOUR_LINKER_HERE>)
set(CMAKE_AR <YOUR_ARCHIVER_HERE>)
set(CMAKE_RANLIB <YOUR_RANLIB_HERE>)

set(COMPILER_ID "other|gcc|clang")

set(CMAKE_FIND_ROOT_PATH_MODE_PROGRAM NEVER)
set(CMAKE_FIND_ROOT_PATH_MODE_LIBRARY ONLY)
set(CMAKE_FIND_ROOT_PATH_MODE_INCLUDE ONLY)
set(CMAKE_FIND_ROOT_PATH_MODE_PACKAGE ONLY)

set(CMAKE_C_COMPILER_WORKS 1)
set(CMAKE_TRY_COMPILE_TARGET_TYPE "STATIC_LIBRARY")