# ZXFoundation gcc toolchain for s390x
set(CMAKE_SYSTEM_NAME Generic)
set(CMAKE_SYSTEM_PROCESSOR s390x)

set(CMAKE_C_COMPILER s390x-ibm-linux-gnu-gcc)
set(CMAKE_CXX_COMPILER s390x-ibm-linux-gnu-g++)
set(CMAKE_ASM_COMPILER s390x-ibm-linux-gnu-gcc)

set(CMAKE_C_LINK_EXECUTABLE "<CMAKE_LINKER> <LINK_FLAGS> <OBJECTS> -o <TARGET> <LINK_LIBRARIES>")
set(CMAKE_CXX_LINK_EXECUTABLE "<CMAKE_LINKER> <LINK_FLAGS> <OBJECTS> -o <TARGET> <LINK_LIBRARIES>")
set(CMAKE_ASM_LINK_EXECUTABLE "<CMAKE_LINKER> <LINK_FLAGS> <OBJECTS> -o <TARGET> <LINK_LIBRARIES>")
set(CMAKE_LINKER s390x-ibm-linux-gnu-ld)
set(CMAKE_AR s390x-ibm-linux-gnu-ar)
set(CMAKE_RANLIB s390x-ibm-linux-gnu-ranlib)
set(CMAKE_OBJCOPY s390x-ibm-linux-gnu-objcopy)
set(ZX_HOST_CC gcc)

set(COMPILER_ID "gcc")

if(NOT DEFINED TARGET_EMULATION_MODE)
    set(TARGET_EMULATION_MODE "elf64_s390" CACHE STRING "Target emulation mode when linking")
endif()

if(NOT DEFINED COMMON_TARGET_TRIPLE)
    set(COMMON_TARGET_TRIPLE "s390x-unknown-none-elf" CACHE STRING "Target triple for z/Architecture (S390X)")
endif()

if(NOT DEFINED MARCH_MODE)
    set(MARCH_MODE "arch9" CACHE STRING "Argument for -march=")
endif()

set(CMAKE_FIND_ROOT_PATH_MODE_PROGRAM NEVER)
set(CMAKE_FIND_ROOT_PATH_MODE_LIBRARY ONLY)
set(CMAKE_FIND_ROOT_PATH_MODE_INCLUDE ONLY)
set(CMAKE_FIND_ROOT_PATH_MODE_PACKAGE ONLY)

set(CMAKE_C_COMPILER_WORKS 1)
set(CMAKE_TRY_COMPILE_TARGET_TYPE "STATIC_LIBRARY")