// SPDX-License-Identifier: Apache-2.0
// tools/zxallsyms_gen.c
//
// Host tool: reads `nm --defined-only --numeric-sort` output from stdin (or
// a file argument) and emits a C source file containing the three zxallsyms
// arrays.
//
// Usage:
//   llvm-nm --defined-only --numeric-sort <kernel.elf> | zxallsyms_gen <out.c>
//   zxallsyms_gen <out.c> <nm_output_file>
//
// nm output format (one symbol per line):
//   <hex_addr> <type_char> <name>
//
// Only symbols with type in {T, t, D, d, R, r, B, b, W, w} are included.
// Symbols whose name starts with '$' or '.' are excluded (linker artifacts).
// When two symbols share the same address, the one with the longer name wins
// (avoids retaining bare section-start labels over real function names).

#include <stdio.h>
#include <stdlib.h>
#include <string.h>
#include <stdint.h>
#include <ctype.h>

#define MAX_SYMS    131072
#define NAME_MAX_LEN 256

typedef struct {
    uint64_t addr;
    char     name[NAME_MAX_LEN];
} sym_t;

static sym_t  g_syms[MAX_SYMS];
static uint32_t g_count = 0;

// ---------------------------------------------------------------------------
// Helpers
// ---------------------------------------------------------------------------

static int is_wanted_type(char t) {
    // Include text, data, rodata, bss, and weak variants.
    switch (t) {
    case 'T': case 't':
    case 'D': case 'd':
    case 'R': case 'r':
    case 'B': case 'b':
    case 'W': case 'w':
        return 1;
    default:
        return 0;
    }
}

static int is_unwanted_name(const char *name) {
    // Skip linker-generated artifacts and compiler internal symbols.
    if (name[0] == '$' || name[0] == '.')
        return 1;
    // Skip the zxallsyms arrays themselves to avoid self-reference.
    if (strncmp(name, "zxallsyms_", 10) == 0)
        return 1;
    return 0;
}

// ---------------------------------------------------------------------------
// Parsing
// ---------------------------------------------------------------------------

static void parse_nm(FILE *in) {
    char line[512];
    while (fgets(line, sizeof(line), in)) {
        // Strip trailing newline.
        size_t len = strlen(line);
        while (len > 0 && (line[len-1] == '\n' || line[len-1] == '\r'))
            line[--len] = '\0';

        // Parse: "<hex_addr> <type> <name>"
        // llvm-nm may also emit " U <name>" for undefined — skip those.
        char *p = line;
        while (*p == ' ') p++;

        // Read hex address.
        char *end;
        uint64_t addr = strtoull(p, &end, 16);
        if (end == p) continue; // no address field

        // Skip whitespace, read type char.
        p = end;
        while (*p == ' ') p++;
        char type_char = *p++;
        if (!is_wanted_type(type_char)) continue;

        // Skip whitespace, read name.
        while (*p == ' ') p++;
        if (*p == '\0') continue;

        if (is_unwanted_name(p)) continue;

        // Truncate name if needed.
        char name[NAME_MAX_LEN];
        strncpy(name, p, NAME_MAX_LEN - 1);
        name[NAME_MAX_LEN - 1] = '\0';

        // Deduplication: if the previous symbol has the same address,
        // keep the one with the longer name.
        if (g_count > 0 && g_syms[g_count - 1].addr == addr) {
            if (strlen(name) > strlen(g_syms[g_count - 1].name))
                strncpy(g_syms[g_count - 1].name, name, NAME_MAX_LEN - 1);
            continue;
        }

        if (g_count >= MAX_SYMS) {
            fprintf(stderr, "zxallsyms_gen: symbol table overflow (> %d symbols)\n",
                    MAX_SYMS);
            exit(1);
        }

        g_syms[g_count].addr = addr;
        strncpy(g_syms[g_count].name, name, NAME_MAX_LEN - 1);
        g_syms[g_count].name[NAME_MAX_LEN - 1] = '\0';
        g_count++;
    }
}

// ---------------------------------------------------------------------------
// Emission
// ---------------------------------------------------------------------------

static void emit(FILE *out) {
    fprintf(out,
        "// SPDX-License-Identifier: Apache-2.0\n"
        "// GENERATED FILE, DO NOT EDIT\n"
        "// Generated by tools/zxallsyms_gen.\n"
        "\n"
        "using u64 = unsigned long long;\n"
        "using u32 = unsigned int;\n"
        "extern \"C\" {\n"
        "\n");

    // Addresses array.
    fprintf(out, "  extern const u64 zxallsyms_addrs[%u] = {\n", g_count);
    for (uint32_t i = 0; i < g_count; i++)
        fprintf(out, "    0x%016llxULL,\n", (unsigned long long)g_syms[i].addr);
    fprintf(out, "};\n\n");

    // Build the name blob and offsets simultaneously.
    // We write the blob as a flat char array; each name is NUL-terminated.
    uint32_t *offsets = malloc(g_count * sizeof(uint32_t));
    if (!offsets) { perror("malloc"); exit(1); }

    // First pass: compute offsets.
    uint32_t blob_pos = 0;
    for (uint32_t i = 0; i < g_count; i++) {
        offsets[i] = blob_pos;
        blob_pos += (uint32_t)strlen(g_syms[i].name) + 1; // +1 for NUL
    }

    // Offsets array.
    fprintf(out, "  extern const u32 zxallsyms_offsets[%u] = {\n", g_count);
    for (uint32_t i = 0; i < g_count; i++)
        fprintf(out, "    %uU,\n", offsets[i]);
    fprintf(out, "};\n\n");

    // Name blob — emit as hex bytes to avoid escaping issues with single quotes, etc.
    fprintf(out, "  extern const char zxallsyms_names[%u] = {\n", blob_pos ? blob_pos : 1);
    for (uint32_t i = 0; i < g_count; i++) {
        const char *n = g_syms[i].name;
        fprintf(out, "    /* [%u] %s */\n    ", offsets[i], n);
        while (*n) {
            fprintf(out, "0x%02x,", (unsigned char)*n++);
        }
        fprintf(out, "0x00,\n");
    }
    if (g_count == 0)
        fprintf(out, "    '\\0'\n");
    fprintf(out, "};\n\n");

    fprintf(out, "  extern const u32 zxallsyms_count = %uU;\n", g_count);
    fprintf(out, "\n}");

    free(offsets);
}

// ---------------------------------------------------------------------------
// main
// ---------------------------------------------------------------------------

int main(int argc, char **argv) {
    if (argc < 2 || argc > 3) {
        fprintf(stderr, "Usage: %s <output.cxx> [nm_output_file]\n", argv[0]);
        return 1;
    }

    FILE *in = stdin;
    if (argc == 3) {
        in = fopen(argv[2], "r");
        if (!in) { perror(argv[2]); return 1; }
    }

    FILE *out = fopen(argv[1], "w");
    if (!out) { perror(argv[1]); return 1; }

    parse_nm(in);
    emit(out);

    if (argc == 3) fclose(in);
    fclose(out);

    fprintf(stderr, "zxallsyms_gen: wrote %u symbols to %s\n", g_count, argv[1]);
    return 0;
}