set(CMAKE_SYSTEM_NAME Generic)
set(CMAKE_SYSTEM_PROCESSOR s390x)
set(CMAKE_C_LINK_EXECUTABLE "<CMAKE_LINKER> <LINK_FLAGS> <OBJECTS> -o <TARGET> <LINK_LIBRARIES>")
set(CMAKE_CXX_LINK_EXECUTABLE "<CMAKE_LINKER> <LINK_FLAGS> <OBJECTS> -o <TARGET> <LINK_LIBRARIES>")
set(CMAKE_ASM_LINK_EXECUTABLE "<CMAKE_LINKER> <LINK_FLAGS> <OBJECTS> -o <TARGET> <LINK_LIBRARIES>")
set(ZX_DEFAULT_CONFIG_FILE "${CMAKE_SOURCE_DIR}/cmake/configs/base.cmake" CACHE STRING "ZXFoundation default configuration script" FORCE)
set(ZX_DEFAULT_TOOLCHAIN_FILE "${CMAKE_SOURCE_DIR}/cmake/toolchain/zxfoundation-clang.cmake" CACHE STRING "ZXFoundation default toolchain file" FORCE)

if (DEFINED ZX_TOOLCHAIN_FILE)
    set(CMAKE_TOOLCHAIN_FILE "${ZX_TOOLCHAIN_FILE}" CACHE STRING "CMake toolchain file" FORCE)
    include("${ZX_TOOLCHAIN_FILE}")
    message(STATUS "zxfoundation::meta: using toolchain file: ${ZX_TOOLCHAIN_FILE}")
elseif(DEFINED CMAKE_TOOLCHAIN_FILE)
    message(FATAL_ERROR "zxfoundation::meta: specifying toolchain file using CMAKE_TOOLCHAIN_FILE has been disabled, please use ZX_TOOLCHAIN_FILE instead")
else()
    include("${ZX_DEFAULT_TOOLCHAIN_FILE}")
    message(WARNING "zxfoundation::meta: toolchain file not specified, using default ${ZX_DEFAULT_TOOLCHAIN_FILE}")
endif()

if (DEFINED ZX_CONFIG_FILE)
    include("${ZX_CONFIG_FILE}")
    message(STATUS "zxfoundation::meta: using configuration file: ${ZX_CONFIG_FILE}")
else ()
    include("${ZX_DEFAULT_CONFIG_FILE}")
    message(WARNING "zxfoundation::meta: no configuration file specified, using default ${ZX_DEFAULT_CONFIG_FILE}")
endif()

if (NOT DEFINED TARGET_EMULATION_MODE)
    set(TARGET_EMULATION_MODE "elf64_s390" CACHE STRING "Target emulation mode when linking")
endif()

if (NOT DEFINED COMMON_TARGET_TRIPLE)
    set(COMMON_TARGET_TRIPLE "s390x-unknown-none-elf" CACHE STRING "Target triple for z/Architecture (S390X)")
endif()

if (NOT DEFINED MARCH_MODE)
    set(MARCH_MODE "z13" CACHE STRING "Argument for -march= and -mtune=")
endif()

set(CMAKE_FIND_ROOT_PATH_MODE_PROGRAM NEVER)
set(CMAKE_FIND_ROOT_PATH_MODE_LIBRARY ONLY)
set(CMAKE_FIND_ROOT_PATH_MODE_INCLUDE ONLY)
set(CMAKE_FIND_ROOT_PATH_MODE_PACKAGE ONLY)

set(CMAKE_C_COMPILER_WORKS 1)
set(CMAKE_CXX_COMPILER_WORKS 1)
set(CMAKE_TRY_COMPILE_TARGET_TYPE "STATIC_LIBRARY")

if (${CMAKE_BINARY_DIR} STREQUAL ${CMAKE_SOURCE_DIR} AND NOT ZX_BUILD_WITHIN_SOURCE)
    message(FATAL_ERROR "zxfoundation::meta: in-source builds are not allowed (ZX_BUILD_WITHIN_SOURCE=ON to override)")
endif()

set(CMAKE_EXPORT_COMPILE_COMMANDS ON)
set(CMAKE_COLOR_DIAGNOSTICS ON)
