# ZXFoundation platform checks (logs for now)
message(STATUS "zxfoundation::build: CMake Generator: ${CMAKE_GENERATOR}")
message(STATUS "zxfoundation::build: CMake Build Type: ${CMAKE_BUILD_TYPE}")
message(STATUS "zxfoundation::build: CMake Source Directory: ${CMAKE_SOURCE_DIR}")
message(STATUS "zxfoundation::build: CMake Binary Directory: ${CMAKE_BINARY_DIR}")
message(STATUS "zxfoundation::build: CMake Current Source Directory: ${CMAKE_CURRENT_SOURCE_DIR}")
message(STATUS "zxfoundation::build: CMake Current Binary Directory: ${CMAKE_CURRENT_BINARY_DIR}")
message(STATUS "zxfoundation::build: CMake Host System Name: ${CMAKE_HOST_SYSTEM_NAME}")
message(STATUS "zxfoundation::build: CMake Host System Processor: ${CMAKE_HOST_SYSTEM_PROCESSOR}")
message(STATUS "zxfoundation::build: CMake sources configured.")